
* Mastering pandas data transformation

Real-world data is messy.
You spend much time to deal with the raw data.
Pandas is a very powerfull library for the data analysis.

In pandas
there are lots of functions for transformating data.
Some of them(merge, concat) are easy to understand.
Some of them(melt, pivot, ...) are like black box even
after you read the documentation.

By the end of this talk, you'll 
 + set up the data analysis platform (jupyter notebook)
 + get some tips on jupyter notebook
 + know how to get started with Pandas if you are new to it. 
 + have better undaterstanding of unstack, stack, melt, pivot,

* Outline

+ quick jupyter notebook intro
  - must installed extension
+ quick pandas intro
  - what can pandas do
  - data transformation
+ tech stack for data analysis
+ clean data: example

* jupyter notebook quick intro

** Try jupyter online

https://try.jupyter.org/

** Get jupyter on your own PC.

https://www.continuum.io/downloads

anaconda is the easiest way to setup your env!

In your terminal, type

#+BEGIN_SRC sh
jupyter notebook
#+END_SRC

** Power your jupyter env

https://github.com/ipython-contrib/jupyter_contrib_nbextensions

#+BEGIN_EXAMPLE
conda install -c conda-forge jupyter_contrib_nbextensions
#+END_EXAMPLE

* pandas quick intro

** Series and DataFrame
  
* pandas data transformation
  
** pivot

drag and drop

https://github.com/nicolaskruchten/jupyter_pivottablejs

http://nicolas.kruchten.com/content/2015/09/jupyter_pivottablejs/

* Example: clean data

[[http://www.jeannicholashould.com/tidy-data-in-python.html][Tidy Data in Python]]
